#!/bin/bash

# killall -q -w -s TERM audacious
killall -q -w -s TERM chrome
# killall -q -w -s TERM qbittorrent
# killall -q -w -s KILL conky

if [[ $1 == "-r" ]]; then
    systemctl reboot
else
    systemctl poweroff
fi

exit 0
