#!/bin/bash
x=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )
if [[ $x+5 -le 154 ]]
then
    pactl set-sink-volume 0 +5%;
    pactl set-sink-mute 0 false
fi
